### ISSUE TITLE
CTF Page

### ISSUE THREAD

**Issue by Daxorinator** [ugcompsoc/compsoc.ie#24]
Review draft CTF page with @Laan33 and @addmmyyyy, to be ready for CTF Launch Date

**Comment by Laan33** [comment]
I'm finishing the blurb for the CTF page today, will be from the CTF blurb google doc.

For the poster, I'm waiting on keith, but I believe it's a portrait poster similar to last years.

**Comment by Laan33** [comment]
Just waiting on the poster to launch this fully

**Comment by Daxorinator** [comment]
Can we close this now?

**Comment by Laan33** [comment]
yes I think it's good to go
