### ISSUE TITLE
Remove unnecessary branches

### ISSUE THREAD

**Issue by pan-grayza** [ugcompsoc/compsoc.ie#27]
I see there is 8 branches but only 2 is used. I think we can clean up old ones. I myself am not sure what branches you still need, so I'd like someone who knows, to do this.

**Comment by Daxorinator** [comment]
Most are related to open PRs - I've removed "PreBICS-Updates" as its no longer needed

**Comment by Daxorinator** [comment]
Closing as we've cleaned up the CTF related branches
